import {
  Kategori,
  Urun,
  Danisman,
  Kampanya,
  IletisimKisi,
  Siparis,
  SiteAyarlari,
  Profile,
} from "./types";

export const MOCK_DANISMANLAR: Danisman[] = [
  {
    id: "dan-1",
    ad_soyad: "Mustafa Köprülü",
    telefon: "0532 555 10 01",
    aktif: true,
  },
  {
    id: "dan-2",
    ad_soyad: "Serpil Köprülü",
    telefon: "0533 444 20 02",
    aktif: true,
  },
  {
    id: "dan-3",
    ad_soyad: "Ahmet Yılmaz (Saha Danışmanı)",
    telefon: "0530 111 30 03",
    aktif: true,
  },
];

export const MOCK_PROFILES: Profile[] = [
  {
    id: "usr-admin",
    username: "admin",
    role: "admin",
    ad_soyad: "Yönetici",
    firma_adi: "Artı Temizlik Züccaciye Merkez",
    telefon: "0532 555 10 01",
    adres: "Saray Mah. İnönü Cad. No:45 Anamur / Mersin",
    created_at: "2025-01-01T08:00:00Z",
  },
  {
    id: "usr-1",
    username: "anamurotel",
    role: "musteri",
    danisman_id: "dan-1",
    ad_soyad: "Kemal Bey",
    firma_adi: "Anamur Resort Otel",
    telefon: "0544 123 45 67",
    adres: "İskele Mah. Sahil Cad. No:12 Anamur / Mersin",
    created_at: "2025-02-10T10:30:00Z",
  },
  {
    id: "usr-2",
    username: "akdenizmarket",
    role: "musteri",
    danisman_id: "dan-2",
    ad_soyad: "Hüseyin Akdeniz",
    firma_adi: "Akdeniz Süpermarket",
    telefon: "0535 987 65 43",
    adres: "Yeşilyurt Mah. Çarşı İçi No:8 Anamur / Mersin",
    created_at: "2025-02-15T14:15:00Z",
  },
];

export const MOCK_KATEGORILER: Kategori[] = [
  {
    id: "kat-1",
    ad: "Endüstriyel & Genel Temizlik",
    slug: "endustriyel-genel-temizlik",
    sira: 1,
    icon_name: "Sparkles",
    aktif: true,
  },
  {
    id: "kat-2",
    ad: "Kağıt Grubu & Dispenserler",
    slug: "kagit-grubu",
    sira: 2,
    icon_name: "ScrollText",
    aktif: true,
  },
  {
    id: "kat-3",
    ad: "Çöp Torbaları & Poşetler",
    slug: "cop-torbalari",
    sira: 3,
    icon_name: "Trash2",
    aktif: true,
  },
  {
    id: "kat-4",
    ad: "Mop & Temizlik Ekipmanları",
    slug: "mop-ekipmanlari",
    sira: 4,
    icon_name: "Brush",
    aktif: true,
  },
  {
    id: "kat-5",
    ad: "Züccaciye & Mutfak Gereçleri",
    slug: "zuccaciye-mutfak",
    sira: 5,
    icon_name: "UtensilsCrossed",
    aktif: true,
  },
  {
    id: "kat-6",
    ad: "Kişisel Hijyen & Sıvı Sabunlar",
    slug: "kisisel-hijyen",
    sira: 6,
    icon_name: "Droplets",
    aktif: true,
  },
  {
    id: "kat-7",
    ad: "Kullan-At Ambalaj Ürünleri",
    slug: "kullan-at-ambalaj",
    sira: 7,
    icon_name: "Package",
    aktif: true,
  },
];

export const MOCK_URUNLER: Urun[] = [
  {
    id: "urn-1",
    ad: "Ultra Yoğun Kıvamlı Çamaşır Suyu (20 Kg)",
    kategori_id: "kat-1",
    fiyat: 460.0,
    birim: "Bidon",
    aciklama: "Klor bazlı, yüzeyleri dezenfekte eden profesyonel hijyenik temizleyici. Otel, hastane ve restoranlar için ideal.",
    gorsel_url: "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=600&auto=format&fit=crop&q=80",
    aktif: true,
    cok_satan: true,
    haftanin_urunu: false,
    stok_durumu: "var",
  },
  {
    id: "urn-2",
    ad: "Endüstriyel Bulaşık Makinesi Deterjanı (20 L)",
    kategori_id: "kat-1",
    fiyat: 780.0,
    birim: "Bidon",
    aciklama: "Sanayi tipi bulaşık makineleri için ağır yağ çözücü ve kireç önleyici özel formül.",
    gorsel_url: "https://images.unsplash.com/photo-1584813470613-5b1c1cad3d69?w=600&auto=format&fit=crop&q=80",
    aktif: true,
    cok_satan: true,
    haftanin_urunu: true,
    stok_durumu: "var",
  },
  {
    id: "urn-3",
    ad: "Z Katlama Fotoselli Havlu (12'li Koli)",
    kategori_id: "kat-2",
    fiyat: 590.0,
    birim: "Koli",
    aciklama: "%100 saf selüloz, çift katlı dayanıklı dispenser kağıt havlu.",
    gorsel_url: "https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=600&auto=format&fit=crop&q=80",
    aktif: true,
    cok_satan: true,
    haftanin_urunu: false,
    stok_durumu: "var",
  },
  {
    id: "urn-4",
    ad: "Jumbo Rulo Tuvalet Kağıdı (12 Rulo)",
    kategori_id: "kat-2",
    fiyat: 440.0,
    birim: "Koli",
    aciklama: "Dispenser uyumlu, ekonomik ve uzun metrajlı kurumsal tuvalet kağıdı.",
    gorsel_url: "https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=600&auto=format&fit=crop&q=80",
    aktif: true,
    cok_satan: false,
    haftanin_urunu: true,
    stok_durumu: "var",
  },
  {
    id: "urn-5",
    ad: "Büyük Boy Ağır Hizmet Çöp Torbası (80x110 cm)",
    kategori_id: "kat-3",
    fiyat: 320.0,
    birim: "Koli (10 Rulo)",
    aciklama: "Sızdırmaz kaynaklı, dayanıklı siyah battal boy konteyner ve dış mekan çöp torbası.",
    gorsel_url: "https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=600&auto=format&fit=crop&q=80",
    aktif: true,
    cok_satan: true,
    haftanin_urunu: false,
    stok_durumu: "var",
  },
  {
    id: "urn-6",
    ad: "Döner Başlıklı Çift Kovalı Mop Arabası (25 L)",
    kategori_id: "kat-4",
    fiyat: 1150.0,
    birim: "Adet",
    aciklama: "Temiz ve kirli su bölmeli, dayanıklı pres sistemli profesyonel kat temizlik arabası.",
    gorsel_url: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=600&auto=format&fit=crop&q=80",
    aktif: true,
    cok_satan: false,
    haftanin_urunu: true,
    stok_durumu: "var",
  },
  {
    id: "urn-7",
    ad: "Mikrofiber Zemin ve Cam Bezi (10'lu Paket)",
    kategori_id: "kat-4",
    fiyat: 185.0,
    birim: "Paket",
    aciklama: "40x40 cm ebatlarında, iz ve tüy bırakmayan yüksek emici mikrofiber temizlik bezi.",
    gorsel_url: "https://images.unsplash.com/photo-1585421514782-b7e6717585a0?w=600&auto=format&fit=crop&q=80",
    aktif: true,
    cok_satan: true,
    haftanin_urunu: false,
    stok_durumu: "var",
  },
  {
    id: "urn-8",
    ad: "Borosilikat Isıya Dayanıklı Cam Çay Bardağı Seti (12'li)",
    kategori_id: "kat-5",
    fiyat: 340.0,
    birim: "Kutu",
    aciklama: "Geleneksel ince belli formda, çizilmeye ve bulaşık makinesine dayanıklı züccaciye serisi.",
    gorsel_url: "https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=600&auto=format&fit=crop&q=80",
    aktif: true,
    cok_satan: true,
    haftanin_urunu: true,
    stok_durumu: "var",
  },
  {
    id: "urn-9",
    ad: "Paslanmaz Çelik Çay Kazanı ve Termos (15 L)",
    kategori_id: "kat-5",
    fiyat: 2450.0,
    birim: "Adet",
    aciklama: "İşletmeler ve kahvehaneler için çift cidarlı ısı yalıtımlı profesyonel çay kazanı.",
    gorsel_url: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=600&auto=format&fit=crop&q=80",
    aktif: true,
    cok_satan: false,
    haftanin_urunu: false,
    stok_durumu: "var",
  },
  {
    id: "urn-10",
    ad: "Nemlendiricili Gliserinli Sıvı El Sabunu (20 L)",
    kategori_id: "kat-6",
    fiyat: 520.0,
    birim: "Bidon",
    aciklama: "Cilde uyumlu pH 5.5, ferah lavanta ve okyanus kokulu dispenser el sabunu.",
    gorsel_url: "https://images.unsplash.com/photo-1608248597359-52e6900f07fa?w=600&auto=format&fit=crop&q=80",
    aktif: true,
    cok_satan: true,
    haftanin_urunu: false,
    stok_durumu: "var",
  },
  {
    id: "urn-11",
    ad: "Karton Çay & Kahve Bardağı 7 Oz (1000'li Koli)",
    kategori_id: "kat-7",
    fiyat: 480.0,
    birim: "Koli",
    aciklama: "Sızdırmaz iç kaplama, sıcak ve soğuk içecekler için yüksek mukavemetli kullan-at bardak.",
    gorsel_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80",
    aktif: true,
    cok_satan: true,
    haftanin_urunu: false,
    stok_durumu: "var",
  },
  {
    id: "urn-12",
    ad: "Kilitli Şeffaf Ambalaj Torbası (1000 Adet)",
    kategori_id: "kat-7",
    fiyat: 210.0,
    birim: "Paket",
    aciklama: "Gıda temasına uygun, hava geçirmez güvenilir tık-tık kilit mekanizmalı torba.",
    gorsel_url: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&auto=format&fit=crop&q=80",
    aktif: true,
    cok_satan: false,
    haftanin_urunu: false,
    stok_durumu: "var",
  },
];

export const MOCK_KAMPANYALAR: Kampanya[] = [
  {
    id: "kmp-1",
    baslik: "İşletmelere Özel Toplu Alım İndirimi",
    aciklama: "Otel, restoran ve eğitim kurumlarına toptan koli alımlarında koli başı avantajlı net bayi fiyatları.",
    gorsel_url: "https://images.unsplash.com/photo-1584813470613-5b1c1cad3d69?w=800&auto=format&fit=crop&q=80",
    cta_link: "/kampanya/kmp-1",
    cta_text: "Fırsat Ürünleri",
    badge_text: "TOPTAN AVANTAJ",
    sira: 1,
    aktif: true,
    urun_ids: ["urn-1", "urn-2", "urn-3", "urn-6", "urn-7"],
  },
  {
    id: "kmp-2",
    baslik: "Züccaciye & Mutfak Gereçlerinde Sezon Yenilikleri",
    aciklama: "Anamur bölgesi işletmelerine ve hanelerine dayanıklı cam, porselen ve çelik servis ürünleri.",
    gorsel_url: "https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=800&auto=format&fit=crop&q=80",
    cta_link: "/kampanya/kmp-2",
    cta_text: "Züccaciye Kataloğu",
    badge_text: "YENİ KOLEKSİYON",
    sira: 2,
    aktif: true,
    urun_ids: ["urn-8", "urn-9"],
  },
  {
    id: "kmp-3",
    baslik: "Hızlı Dağıtım & Yerinde Teslimat",
    aciklama: "Anamur, Bozyazı ve Aydıncık bölgesine kendi servis araçlarımızla aynı gün veya ertesi gün elden teslim.",
    gorsel_url: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80",
    cta_link: "/iletisim",
    cta_text: "Danışmana Ulaşın",
    badge_text: "BÖLGESEL SERVİS",
    sira: 3,
    aktif: true,
    urun_ids: ["urn-4", "urn-5", "urn-10", "urn-11", "urn-12"],
  },
];

export const MOCK_ILETISIM_KISILERI: IletisimKisi[] = [
  {
    id: "ilt-1",
    ad_soyad: "Mustafa Köprülü",
    unvan: "Genel Koordinatör & Toptan Satış",
    telefon: "0532 555 10 01",
    sira: 1,
  },
  {
    id: "ilt-2",
    ad_soyad: "Serpil Köprülü",
    unvan: "Mağaza & Müşteri İlişkileri",
    telefon: "0533 444 20 02",
    sira: 2,
  },
  {
    id: "ilt-3",
    ad_soyad: "Artı Temizlik Ofis",
    unvan: "Sipariş & Muhasebe Hattı",
    telefon: "0324 814 00 00",
    sira: 3,
  },
];

export const MOCK_AYARLAR: SiteAyarlari = {
  id: "00000000-0000-0000-0000-000000000001",
  cok_satanlar_modu: "manuel",
  haftanin_urunleri_modu: "manuel",
};

export const MOCK_SIPARISLER: Siparis[] = [
  {
    id: "sip-1001",
    user_id: "usr-1",
    danisman_id: "dan-1",
    status: "onaylandi",
    toplam_tutar: 3260.0,
    siparis_notu: "Sabah 10:00'dan önce otele teslim edilirse çok seviniriz.",
    created_at: "2025-05-10T09:14:00Z",
    musteri: MOCK_PROFILES[1],
    danisman: MOCK_DANISMANLAR[0],
    kalemler: [
      {
        id: "kal-1",
        siparis_id: "sip-1001",
        urun_id: "urn-1",
        adet: 4,
        birim_fiyat: 460.0,
        urun: MOCK_URUNLER[0],
      },
      {
        id: "kal-2",
        siparis_id: "sip-1001",
        urun_id: "urn-3",
        adet: 2,
        birim_fiyat: 590.0,
        urun: MOCK_URUNLER[2],
      },
      {
        id: "kal-3",
        siparis_id: "sip-1001",
        urun_id: "urn-10",
        adet: 1,
        birim_fiyat: 520.0,
        urun: MOCK_URUNLER[9],
      },
    ],
  },
  {
    id: "sip-1002",
    user_id: "usr-2",
    danisman_id: "dan-2",
    status: "beklemede",
    toplam_tutar: 1420.0,
    siparis_notu: "Market arka deposuna bırakılacak.",
    created_at: "2025-05-12T15:45:00Z",
    musteri: MOCK_PROFILES[2],
    danisman: MOCK_DANISMANLAR[1],
    kalemler: [
      {
        id: "kal-4",
        siparis_id: "sip-1002",
        urun_id: "urn-5",
        adet: 3,
        birim_fiyat: 320.0,
        urun: MOCK_URUNLER[4],
      },
      {
        id: "kal-5",
        siparis_id: "sip-1002",
        urun_id: "urn-11",
        adet: 1,
        birim_fiyat: 480.0,
        urun: MOCK_URUNLER[10],
      },
    ],
  },
];
